sudo: required

services:
    - docker

language: minimal

addons:
    apt:
        packages:
            - docker-ce

before_install:
    - docker run --detach --init --name cont -v $PWD:/repo:rw -w /repo fedora:28 sleep infinity

script:
    - docker exec cont /repo/.ci/script

notifications:
    email: false
